# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-11 23:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Student_ID', models.CharField(max_length=8, unique=True)),
                ('DOB', models.DateField(help_text='Kindly Enter Date in this format: YYYY/MM/DD', verbose_name='Date Of Birth')),
                ('Branch', models.CharField(choices=[('aero', 'Aerospace'), ('civil', 'Civil'), ('cse', 'Computer Science'), ('ece', 'Electronics & Communication'), ('elec', 'Electrical'), ('mech', 'Mechanical'), ('meta', 'Materials & Metallurgical'), ('prod', 'Production & Industrial')], default='aero', max_length=4)),
                ('Year_Of_Study', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], default='1', max_length=1)),
                ('Address', models.TextField()),
                ('Contact_Number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1111111111)])),
            ],
        ),
    ]
