# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-13 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180312_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsignup',
            name='Address',
            field=models.CharField(max_length=300),
        ),
    ]
