# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-28 17:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20180313_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsignup',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentsignup',
            name='DOB',
            field=models.DateField(verbose_name='Date Of Birth'),
        ),
    ]
