# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-30 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180329_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Faculty_ID', models.CharField(max_length=8, unique=True)),
                ('Department', models.CharField(choices=[('aero', 'Aerospace'), ('civil', 'Civil'), ('cse', 'Computer Science'), ('ece', 'Electronics & Communication'), ('elec', 'Electrical'), ('mech', 'Mechanical'), ('meta', 'Materials & Metallurgical'), ('prod', 'Production & Industrial')], default='aero', max_length=4)),
                ('Address', models.CharField(max_length=300)),
                ('Contact_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('Designation', models.CharField(choices=[('prof', 'Professor'), ('asso', 'Associate Professor'), ('assi', 'Assistant Professor'), ('inst', 'Instructor')], default='prof', max_length=4)),
                ('Qualification', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameModel(
            old_name='StudentSignup',
            new_name='Student',
        ),
    ]
