# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-10 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthStudentDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.CharField(max_length=8, unique=True)),
                ('Name', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('branch', models.CharField(choices=[('aero', 'Aerospace'), ('civil', 'Civil'), ('cse', 'Computer Science'), ('ece', 'Electronics & Communication'), ('elec', 'Electrical'), ('mech', 'Mechanical'), ('meta', 'Materials & Metallurgical'), ('prod', 'Production & Industrial')], default='aero', max_length=4)),
                ('year', models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], default='1')),
            ],
        ),
    ]
