# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-10 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepUpdate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authstudentdb',
            name='year',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], default='1', max_length=1),
        ),
    ]
