# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-10 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DepUpdate', '0002_auto_20180310_2019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthStudentDB',
            new_name='AuthStudent',
        ),
    ]
