# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-10 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepUpdate', '0003_auto_20180311_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseID', models.CharField(max_length=6)),
                ('CourseName', models.CharField(max_length=50)),
                ('Credits', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='authstudent',
            options={'ordering': ['SID']},
        ),
    ]
