# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-10 23:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepUpdate', '0005_auto_20180311_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='CourseID',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Credits',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
    ]
