# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-10 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DepUpdate', '0006_auto_20180311_0505'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='courses',
            new_name='course',
        ),
    ]
